### ISSUE TITLE
Can't reference the internal type or namespace to interact with it

### ISSUE THREAD

**Issue by MostHated** [baba-s/unity-project-window-menu-customizer#1]
Hey there,
I am a big fan of your tools, I am using several of them in my current project. I am having a bit of an issue with this one though, as I was working on making central settings window for a number of things but since I was using this as a package and I believe the ScriptableObject classes are internal I can't get reference to ProjectWindowMenuSettings so that add it to my menu. 

I could always clone the package, import it, then modify the files but that sort of defeats the purpose of using a Unity package. Is it possible to expose some parts of the package to allow this more easily? 

I definitely appreciate all the work you put into these packages, they are great! At the moment, I am using this one, the customizable toolbar, enum utils, scope, sequencetask and I just recently added symbol and the enum generator, but didn't get a chance to set them up yet. 

Thanks!
-MH

**Comment by baba-s** [comment]
@MostHated 

Thank you for message!

> Is it possible to expose some parts of the package to allow this more easily?

I try to keep my editor extension packages internal. The reason for this is to avoid unnecessary asmdef references.
But I understand your request very well. I need some time to think about changing internal to public. :thinking: 

I can't promise to change from internal to public any time soon, but many of my packages are "no license".
So, for example, it's not a problem for you to customize "UniProjectWindowMenuCustomizer" and publish it to your repository.
Then you are free to customize the package and install it from the Unity Package Manager. :bow:

**Comment by MostHated** [comment]
I appreciate the reply. That is no problem, I can certainly understand. I took a look at the license just after I wrote my question and noticed that, so I went ahead and did the changes to ProjectWindow and CustomizableToolbar and everything is working as I had wanted now. 👍
